version: 2.1

orbs:
  zappa: borb/zappa@0.0.2

workflows:
  deploy-demo:
    jobs:
      - zappa/zappa-deploy:
          stage: staging
          filters:
            branches:
              only: master
      - zappa/zappa-deploy:
          stage: borb-test
          filters:
            branches:
              only: borb-test

