version: 2.1

orbs:
  zappa: borb/zappa@dev:borb

workflows:
  deploy-demo:
    jobs:
      - zappa/zappa-deploy:
          stage: staging
          filters:
            branches:
              only: master
      - zappa/zappa-deploy:
          stage: borb
          filters:
            branches:
              only: borb-test

