version: 2.1

orbs:
  zappa: borb/zappa@dev:add-distinct-deploy-and-update-steps

workflows:
  deploy-demo:
    jobs:
      - zappa/zappa-deploy:
          stage: staging
          filters:
            branches:
              only: master
      - zappa/zappa-deploy:
          stage: borb
          python_version: "3.6.6"
          filters:
            branches:
              only: borb-test

