version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run: pipenv install
      - run:
          name: Deploying to Staging
          command: |
            set +e
            STATUS=$(pipenv run zappa status staging -j 2>&1)
            set -e
            if $(echo $STATUS | jq . 2>/dev/null);
            then pipenv run zappa update staging;
            elif [[ "$STATUS" == *"have you deployed yet?" ]];
            then pipenv run zappa deploy staging;
            else echo "$STATUS\nUnknown error!" && exit 1
            fi
