version: 2.1

orbs:
  zappa: borb/zappa@dev:master

workflows:
  deploy-demo:
    jobs:
      - zappa/zappa-deploy:
          stage: staging
          filters:
            branches:
              only: master
      - zappa/zappa-deploy:
          all_stages: true
          python_version: "2.7"
          filters:
            branches:
              only: borb-test

