version: 2.1

orbs:
  zappa: borb/zappa@0.0.1

workflows:
  deploy-demo:
    jobs:
      - zappa/zappa-deploy:
          stage: staging
          filters:
            branches:
              only: master
